out_tag = ["<output>", "/output>"]
ex_out_tag = ["<expected_output>", "/expected_output>"]
max_security_scan_retries = 3

css = """
#red {background-color: #FA9F9D}
#amber {background-color: #FFD966}
/* Gradio container */
gradio-app .gradio-container{
 max-width:2240px !important;
 transform:translatex(0px) translatey(0px);
}

/* Script group */
#script-group{
 transform:translatex(0px) translatey(0px);
 overflow:visible;
 min-height:643px;
 height:643px;
}

/* Styler */
#script-group .styler{
 min-height:643px;
 height:643px;
}

/* Unpadded box */
#script-group .block .unpadded_box{
 height:546px;
 min-height:546px;
 max-height:546px;
}

/* Unpadded box */
.contain .gap .unpadded_box{
 min-height:362px !important;
}
/* Min */
#script-group .styler .min{
 min-height:28px;
 height:28px;
 max-height:28px;
}

/* Scroller */
.codemirror-wrapper .cm-editor .cm-scroller{
 height:547px;
 min-height:547px;
 max-height:547px;
}
"""
welcome_message="""
# Welcome to Codenator 🤖️
### Allow me to help you develop secure and robust code
"""
instructions="""
* Select programing language and LLM Model.<br><br>
* Interact with agent through chat to generate and modify code.<br><br>
* Each time agent will generate code, the code will be scanned for security vulnerabilities.<br><br>
* If the code fails security scan it will automatically sent back to agent to modify it. Failed code are not allowed to be executed.<br><br>
* Failed scan results will appear under **Other Outputs**.<br><br>
* You can approve and execute scanned code. The output of that execution will show in the **Output** section.<br><br>
* If the execution resulted in an error, the **Output** section will be colored in red and feed back will be sent to agent. The agent will automatically try to generate new corrected code.<br><br>
* An **Expected Output** generated by agent will also appear under **Other Outputs** section. If *Output* does not match **Expected Output**, the **Output** section will turn yellow.<br><br>
* You can toggle streaming or change model paramaters from the **Parameters** section.<br><br>
"""
output_err_msg = "Output: ❌️ ERROR ❌️"
output_wrn_msg = "Output: ⚠️ WARNING ⚠️ value does not match `Expected Output`"
output_info_msg = "Output:"
scan_fail_msg = "🔍️ Code Security scan status: ⛔️"
scan_pass_msg = "🔍️ Code Security scan status: ✅️"
scan_empty_msg = "🔍️ Code Security scan status: None"
sec_out_err_msg = "Security Scan Output: ❌️ ERROR ❌️"
sec_out_info_msg = "Security Scan Output:"
files_path = "tmp"