max_security_scan_retries = 3

css = """
/* Gradio app */
gradio-app{
 background-color:#eaeaea !important;
 background-image:url("https://images.unsplash.com/photo-1633174524827-db00a6b7bc74?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8Mnx8YW1hem9ufGVufDB8fHx8MTcwMTc2MTE2Mnww&ixlib=rb-4.0.3&q=80&w=2560") !important;
}
/* Prose */
#main-banner .svelte-1ed2p3z .prose{
 transform:translatex(0px) translatey(0px);
}

/* Main banner */
#main-banner {
 color:white;
 background-color: #232F3E;
 border-top-left-radius:0px;
 border-top-right-radius:0px;
 border-bottom-left-radius:0px;
 border-bottom-right-radius:0px;
 padding-left:40px;
 padding-right:40px;
 padding-top:10px;
 padding-bottom:10px;
}
#red {background-color: #FA9F9D}
#amber {background-color: #FFD966}
/* Gradio container */
gradio-app .gradio-container{
 max-width:90% !important;
 width:90% !important;
 transform:translatex(0px) translatey(0px);
 padding-top:0px !important;
}

/* Script group */
#script-group{
 transform:translatex(0px) translatey(0px);
 overflow:visible;
 min-height:493px;
 height:493px;
}

/* Styler */
#script-group .styler{
 min-height:493px;
 height:493px;
}

/* Unpadded box */
#script-group .block .unpadded_box{
 height:396px;
 min-height:396px;
 max-height:396px;
}

/* Unpadded box */
.contain .gap .unpadded_box{
 min-height:301px !important;
}
/* Preview */
.contain .gap .preview{
 max-height:301px;
}

/* Grid wrap */
.contain .gap .grid-wrap{
 max-height:301px !important;
 min-height:301px !important;
}
/* Min */
#script-group .styler .min{
 min-height:28px;
 height:28px;
 max-height:28px;
}

/* Scroller */
.codemirror-wrapper .cm-editor .cm-scroller{
 height:397px;
 min-height:397px;
 max-height:397px;
}
/* Primary */
#script-group .styler .primary{
 min-width:80px;
}

/* Primary */
gradio-app .gradio-container .main .wrap .contain .gap .stretch .gap .stretch .gap #script-group .styler .stretch .primary{
 width:80px !important;
}

/* Secondary */
#script-group .styler .secondary{
 min-width:100px;
}

/* Secondary */
gradio-app .gradio-container .main .wrap .contain .gap .stretch .gap .stretch .gap #script-group .styler .stretch .secondary{
 width:100px !important;
}

/* Tabitem */
.contain .gap .tabitem{
 background-color:#ffffff;
}

/* Text Area */
#chatbot-group label textarea{
 max-height:42px;
}

/* Text Area */
#script-group label textarea{
 max-height:42px;
}
"""
welcome_message="""
<a href="https://aws.amazon.com/what-is-cloud-computing"><img style="color:white; background-color: #232F3E;float: right;" src="https://d0.awsstatic.com/logos/powered-by-aws-white.png" alt="Powered by AWS Cloud Computing"></a>
# <span style="color:white; background-color: #232F3E">Welcome to Codenator 🤖️</span>
### <span style="color:white; background-color: #232F3E">Allow me to help you develop secure and robust code</span>
"""
instructions="""
* Select programing language and LLM Model.<br><br>
* Interact with agent through chat to generate and modify code.<br><br>
* Each time agent will generate code, the code will be scanned for security vulnerabilities.<br><br>
* If the code fails security scan it will automatically sent back to agent to modify it. Failed code are not allowed to be executed.<br><br>
* Failed scan results will appear under **Other Outputs**.<br><br>
* You can approve and execute scanned code. The output of that execution will show in the **Output** section.<br><br>
* If the execution resulted in an error, the **Output** section will be colored in red and feed back will be sent to agent. The agent will automatically try to generate new corrected code.<br><br>
* An **Expected Output** generated by agent will also appear under **Other Outputs** section. If *Output* does not match **Expected Output**, the **Output** section will turn yellow.<br><br>
* You can toggle streaming or change model paramaters from the **Parameters** section.<br><br>
"""
output_err_msg = "Output: ❌️ ERROR ❌️"
output_wrn_msg = "Output: ⚠️ WARNING ⚠️ value does not match `Expected Output`"
output_info_msg = "Output:"
scan_fail_msg = "🔍️ Code Security scan status: ⛔️"
scan_pass_msg = "🔍️ Code Security scan status: ✅️"
scan_empty_msg = "🔍️ Code Security scan status: None"
sec_out_err_msg = "Security Scan Output: ❌️ ERROR ❌️"
sec_out_info_msg = "Security Scan Output:"
files_path = "tmp"
